server:
  port: 8080
  
spring:
  cloud:
    gateway:
      routes:
        - id: movieRoute #Identificando la ruta del service de producto
          uri: http://localhost:8082/ #URL donde se har치 el redirect segun el predicate definido
          predicates: #RReglas de an치lisis de una request
            - Path=/movies/**
        - id: catalogRoute #Identificando la ruta del service de producto
          uri: http://localhost:8084/ #URL donde se har치 el redirect segun el predicate definido
          predicates: #RReglas de an치lisis de una request
            - Path=/catalog/**
            
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

info:
  app:
    name: gateway-service
    description: Parcial de Microservicios
    version: 1.0.0


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
